// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvsQuojrbVUHW5VtyNdG5yc9_vhEQVGPc',
    appId: '1:711557251715:web:83996b8348434e738511b6',
    messagingSenderId: '711557251715',
    projectId: 'harfa-fashion-shop',
    authDomain: 'harfa-fashion-shop.firebaseapp.com',
    storageBucket: 'harfa-fashion-shop.firebasestorage.app',
    measurementId: 'G-50M0GYJTSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2gYb4_kr6jQ41S0I80_lbZbH21h-YmfQ',
    appId: '1:711557251715:android:cb2745300a5b0ff28511b6',
    messagingSenderId: '711557251715',
    projectId: 'harfa-fashion-shop',
    storageBucket: 'harfa-fashion-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Z6vhHPZQ5ZByk0dJlnoKiYtlJRA9_Po',
    appId: '1:711557251715:ios:1d6574086e2d6d888511b6',
    messagingSenderId: '711557251715',
    projectId: 'harfa-fashion-shop',
    storageBucket: 'harfa-fashion-shop.firebasestorage.app',
    iosBundleId: 'com.harfa.fashion.shop',
  );
}
